/* Easter eggs for orrery.gifos.app — space toys that live only on this computer.
   Two extras, filed into the stock folders: a Rocket Lander game and an Alien
   Translator. Both are self-contained and save state in their own gifos.db, so
   a stolen copy keeps working (and remembers) wherever it lands. */
GifOS.addEggs([{
  // ---- Rocket Lander ----------------------------------------------------------
  name: 'Rocket Lander',
  appId: 'lander',
  accent: [255, 160, 60],
  folder: 'Games',
  html: "<!doctype html><html><head><meta charset='utf-8'>"
    + "<meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no'><style>"
    + "html,body{margin:0;height:100%;overflow:hidden;background:var(--bg,#04030a);color:var(--text,#fbf2e4);"
    + "font:14px system-ui,sans-serif;-webkit-user-select:none;user-select:none;touch-action:none}"
    + "#wrap{position:fixed;inset:0;display:flex;flex-direction:column}"
    + "canvas{flex:1;display:block;width:100%}"
    + ".hud{position:absolute;top:10px;left:12px;right:12px;display:flex;justify-content:space-between;"
    + "font:600 13px ui-monospace,monospace;text-shadow:0 1px 3px #000;pointer-events:none}"
    + ".hud b{color:var(--accent,#ffb24d)}"
    + ".msg{position:absolute;top:42%;left:0;right:0;text-align:center;font-size:20px;font-weight:800;"
    + "text-shadow:0 2px 8px #000;pointer-events:none}"
    + ".msg small{display:block;font-size:13px;font-weight:500;color:var(--muted,#c0a888);margin-top:6px}"
    + ".ctrls{display:flex;gap:10px;padding:12px;padding-bottom:calc(12px + env(safe-area-inset-bottom))}"
    + ".ctrls button{flex:1;padding:16px 0;border:1px solid var(--border,#43371f);border-radius:14px;"
    + "background:var(--surface,#140f1e);color:var(--text,#fbf2e4);font:700 20px system-ui;cursor:pointer}"
    + ".ctrls button:active{background:var(--accent,#ffb24d);color:var(--onaccent,#2a1600)}"
    + ".ctrls .thr{flex:1.5}"
    + "</style></head><body><div id='wrap'>"
    + "<canvas id='c'></canvas>"
    + "<div class='hud'><span>FUEL <b id='fuel'>100</b></span><span id='spd'>0 / 0</span>"
    + "<span>BEST <b id='best'>0</b></span></div>"
    + "<div class='msg' id='msg'></div>"
    + "<div class='ctrls'><button id='left'>&#9664;</button>"
    + "<button class='thr' id='thrust'>&#128293; THRUST</button>"
    + "<button id='right'>&#9654;</button></div>"
    + "</div><script>"
    + "var cv=document.getElementById('c'),x=cv.getContext('2d');"
    + "var W=0,H=0,dpr=Math.min(2,window.devicePixelRatio||1);"
    + "function fit(){var r=cv.getBoundingClientRect();W=r.width;H=r.height;cv.width=W*dpr;cv.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0);} "
    + "window.addEventListener('resize',fit);"
    + "var db=window.gifos?gifos.db('lander'):null,best=0;"
    + "if(db)db.subscribe(function(rows){var b=0;(rows||[]).forEach(function(r){if(r&&r.id==='best')b=r.score||0;});best=b;document.getElementById('best').textContent=best;});"
    + "var stars=[];for(var i=0;i<70;i++)stars.push([Math.random(),Math.random()*0.7,Math.random()*1.4+0.3]);"
    + "var g=60,THR=155,ROT=2.6;"
    + "var ship,padX,padW,groundY,over,won,landings;"
    + "function reset(full){fit();groundY=H-70;padW=Math.max(70,W*0.18);padX=40+Math.random()*(W-padW-80);"
    + "ship={x:W*0.5,y:70,vx:(Math.random()*2-1)*20,vy:0,a:0,fuel:100};over=false;won=false;if(full)landings=0;setMsg('');}"
    + "var keys={l:false,r:false,t:false};"
    + "function bind(id,k){var b=document.getElementById(id);"
    + "var on=function(e){e.preventDefault();if(over){reset(over&&!won?true:false);return;}keys[k]=true;};"
    + "var off=function(e){e.preventDefault();keys[k]=false;};"
    + "b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);"
    + "b.addEventListener('pointerleave',off);b.addEventListener('pointercancel',off);}"
    + "bind('left','l');bind('right','r');bind('thrust','t');"
    + "window.addEventListener('keydown',function(e){if(e.key==='ArrowLeft')keys.l=true;else if(e.key==='ArrowRight')keys.r=true;"
    + "else if(e.key===' '||e.key==='ArrowUp'){keys.t=true;if(over)reset(!won);}e.preventDefault?e.preventDefault():0;});"
    + "window.addEventListener('keyup',function(e){if(e.key==='ArrowLeft')keys.l=false;else if(e.key==='ArrowRight')keys.r=false;else if(e.key===' '||e.key==='ArrowUp')keys.t=false;});"
    + "function setMsg(t,s){document.getElementById('msg').innerHTML=t?(t+(s?('<small>'+s+'</small>'):'')):'';}"
    + "function landOk(){return Math.abs(ship.vx)<26&&ship.vy<42&&Math.abs(ship.a)<0.26&&ship.x>padX&&ship.x<padX+padW;}"
    + "var last=performance.now();"
    + "function loop(now){var dt=Math.min(0.05,(now-last)/1000);last=now;"
    + "if(!over){if(keys.l)ship.a-=ROT*dt;if(keys.r)ship.a+=ROT*dt;"
    + "if(keys.t&&ship.fuel>0){ship.vx+=Math.sin(ship.a)*THR*dt;ship.vy-=Math.cos(ship.a)*THR*dt;ship.fuel=Math.max(0,ship.fuel-20*dt);}"
    + "ship.vy+=g*dt;ship.x+=ship.vx*dt;ship.y+=ship.vy*dt;"
    + "if(ship.x<10){ship.x=10;ship.vx=Math.abs(ship.vx)*0.3;}if(ship.x>W-10){ship.x=W-10;ship.vx=-Math.abs(ship.vx)*0.3;}"
    + "if(ship.y>=groundY-10){ship.y=groundY-10;over=true;won=landOk();"
    + "if(won){landings++;setMsg('&#128075; Touchdown!','Landings: '+landings+' \\u2014 tap THRUST to launch again');"
    + "if(landings>best&&db){best=landings;db.put({id:'best',score:best});document.getElementById('best').textContent=best;}}"
    + "else{setMsg('&#128165; Crashed',(ship.x<padX||ship.x>padX+padW)?'Aim for the lit pad \\u2014 tap THRUST to retry':'Too fast \\u2014 ease down gently, tap THRUST to retry');}}}"
    + "document.getElementById('fuel').textContent=Math.round(ship.fuel);"
    + "document.getElementById('spd').textContent=Math.round(ship.vx)+' / '+Math.round(ship.vy);"
    + "draw();requestAnimationFrame(loop);}"
    + "function draw(){x.clearRect(0,0,W,H);"
    + "x.fillStyle='#05040d';x.fillRect(0,0,W,H);"
    + "for(var i=0;i<stars.length;i++){var s=stars[i];x.globalAlpha=0.4+0.6*Math.abs(Math.sin(i+last/700));"
    + "x.fillStyle='#cfe0ff';x.fillRect(s[0]*W,s[1]*H,s[2],s[2]);}x.globalAlpha=1;"
    + "x.fillStyle='#1a1330';x.fillRect(0,groundY,W,H-groundY);"
    + "x.strokeStyle='#3a2d5a';x.lineWidth=2;x.beginPath();x.moveTo(0,groundY);"
    + "for(var gx=0;gx<=W;gx+=24){var yy=groundY+((gx>padX-6&&gx<padX+padW+6)?0:(Math.sin(gx*0.7)*4-6));x.lineTo(gx,yy);}x.stroke();"
    + "var pc=getComputedStyle(document.body).getPropertyValue('--accent')||'#ffb24d';"
    + "x.fillStyle=pc;x.fillRect(padX,groundY-3,padW,4);"
    + "x.globalAlpha=0.5+0.5*Math.abs(Math.sin(last/300));x.fillRect(padX,groundY-3,4,-8);x.fillRect(padX+padW-4,groundY-3,4,-8);x.globalAlpha=1;"
    + "x.save();x.translate(ship.x,ship.y);x.rotate(ship.a);"
    + "if(keys.t&&ship.fuel>0&&!over){x.fillStyle='#ffb020';x.beginPath();x.moveTo(-5,9);x.lineTo(5,9);"
    + "x.lineTo(0,9+10+Math.random()*8);x.closePath();x.fill();}"
    + "x.fillStyle='#eef1fb';x.beginPath();x.moveTo(0,-13);x.lineTo(8,9);x.lineTo(-8,9);x.closePath();x.fill();"
    + "x.fillStyle=pc;x.beginPath();x.moveTo(8,9);x.lineTo(13,15);x.lineTo(6,9);x.closePath();x.fill();"
    + "x.beginPath();x.moveTo(-8,9);x.lineTo(-13,15);x.lineTo(-6,9);x.closePath();x.fill();"
    + "x.fillStyle='#7fd0ff';x.beginPath();x.arc(0,-1,3.2,0,7);x.fill();x.restore();}"
    + "reset(true);requestAnimationFrame(loop);"
    + "</script></body></html>",
  // Your best landing is your own — private, kept with the app.
  manifest: { data: { lander: { visibility: 'private' } } },
}, {
  // ---- Alien Translator -------------------------------------------------------
  name: 'Alien Translator',
  appId: 'aliens',
  accent: [120, 240, 160],
  folder: 'Studio',
  html: "<!doctype html><html><head><meta charset='utf-8'>"
    + "<meta name='viewport' content='width=device-width,initial-scale=1'><style>"
    + "body{margin:0;padding:16px;background:var(--bg,#04030a);color:var(--text,#fbf2e4);"
    + "font:15px system-ui,sans-serif}"
    + "h1{font-size:1.15rem;margin:0 0 .3rem}"
    + "p.sub{color:var(--muted,#c0a888);font-size:13px;margin:0 0 14px}"
    + "textarea{width:100%;box-sizing:border-box;min-height:70px;padding:12px;border-radius:12px;"
    + "border:1px solid var(--border,#43371f);background:var(--surface,#140f1e);color:inherit;font:inherit;resize:vertical}"
    + ".row{display:flex;gap:8px;margin-top:10px}"
    + "button{padding:10px 14px;border:0;border-radius:10px;background:var(--accent,#7ef0a0);"
    + "color:var(--onaccent,#08210f);font:inherit;font-weight:700;cursor:pointer}"
    + "button.ghost{background:var(--surface,#140f1e);color:var(--text,#fbf2e4);border:1px solid var(--border,#43371f)}"
    + ".out{margin-top:14px;padding:14px;min-height:54px;border-radius:12px;background:rgba(126,240,160,.07);"
    + "border:1px solid var(--border,#43371f);line-height:1.9;overflow-wrap:anywhere}"
    + ".out svg{vertical-align:middle;margin:0 1px}"
    + ".saved{margin-top:16px}.saved h2{font-size:.85rem;color:var(--muted,#c0a888);margin:0 0 6px;text-transform:uppercase;letter-spacing:.05em}"
    + ".chip{display:block;width:100%;text-align:left;margin:0 0 6px;padding:8px 10px;border-radius:9px;"
    + "background:var(--surface,#140f1e);border:1px solid var(--border,#43371f);color:var(--text,#fbf2e4);cursor:pointer;font-size:13px}"
    + ".legend{margin-top:16px;font-size:11px;color:var(--muted,#c0a888)}"
    + ".legend span{display:inline-block;margin:2px 6px 2px 0;white-space:nowrap}"
    + "</style></head><body>"
    + "<h1>&#128125; Alien Translator</h1>"
    + "<p class='sub'>Type in Earthling; read it back in Zorblaxian. Every glyph is drawn from the letter, so your friends can decode it with the key below.</p>"
    + "<textarea id='t' placeholder='greetings earthling'></textarea>"
    + "<div class='row'><button id='send'>&#128225; Transmit</button><button class='ghost' id='save'>Save</button></div>"
    + "<div class='out' id='o'></div>"
    + "<div class='saved'><h2>Saved transmissions</h2><div id='list'></div></div>"
    + "<div class='legend' id='legend'></div>"
    + "<script>"
    + "var A='abcdefghijklmnopqrstuvwxyz';"
    + "function glyph(ch){var i=A.indexOf(ch);if(i<0)return null;"
    + "var seed=(i*2654435761)>>>0;function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}"
    + "var col='#7ef0a0';var p='';var n=2+Math.floor(rnd()*3);"
    + "for(var k=0;k<n;k++){var y1=3+rnd()*18,y2=3+rnd()*18,mx=5+rnd()*14;"
    + "p+=\"<path d='M3 \"+y1.toFixed(1)+\" Q\"+mx.toFixed(1)+' '+((y1+y2)/2+(rnd()*10-5)).toFixed(1)+' 21 '+y2.toFixed(1)+\"' fill='none' stroke='\"+col+\"' stroke-width='2' stroke-linecap='round'/>\";}"
    + "var dots=Math.floor(rnd()*3);for(var d=0;d<dots;d++)p+=\"<circle cx='\"+(4+rnd()*16).toFixed(1)+\"' cy='\"+(4+rnd()*16).toFixed(1)+\"' r='1.6' fill='\"+col+\"'/>\";"
    + "return \"<svg width='22' height='24' viewBox='0 0 24 24'>\"+p+'</svg>';}"
    + "function toAlien(s){var out='';for(var j=0;j<s.length;j++){var ch=s[j].toLowerCase();var gg=glyph(ch);"
    + "if(gg)out+=gg;else if(ch===' ')out+=\"<span style='display:inline-block;width:12px'></span>\";else out+=\"<span style='opacity:.6'>\"+(ch.replace(/</g,'&lt;'))+'</span>';}return out;}"
    + "var t=document.getElementById('t'),o=document.getElementById('o');"
    + "function render(){o.innerHTML=toAlien(t.value||'')||\"<span style='color:var(--muted,#c0a888)'>Your transmission appears here.</span>\";}"
    + "t.addEventListener('input',render);document.getElementById('send').onclick=render;"
    + "var db=window.gifos?gifos.db('aliens'):null;"
    + "document.getElementById('save').onclick=function(){var v=(t.value||'').trim();if(!v)return;"
    + "if(db)db.put({id:'m'+Date.now(),text:v,at:Date.now()});};"
    + "function showList(rows){var msgs=(rows||[]).filter(function(r){return r&&r.text;}).sort(function(a,b){return (b.at||0)-(a.at||0);}).slice(0,8);"
    + "var el=document.getElementById('list');if(!msgs.length){el.innerHTML=\"<span style='color:var(--muted,#c0a888);font-size:13px'>Nothing saved yet.</span>\";return;}"
    + "el.innerHTML='';msgs.forEach(function(m){var b=document.createElement('button');b.className='chip';b.textContent=m.text;"
    + "b.onclick=function(){t.value=m.text;render();window.scrollTo(0,0);};el.appendChild(b);});}"
    + "if(db&&db.subscribe)db.subscribe(showList);else showList([]);"
    + "var lg=document.getElementById('legend'),h='<b>Key:</b> ';for(var i=0;i<A.length;i++)h+=\"<span>\"+glyph(A[i])+A[i]+'</span>';lg.innerHTML=h;"
    + "render();"
    + "</script></body></html>",
  // Saved transmissions are your own — private, kept with the app.
  manifest: { data: { aliens: { visibility: 'private' } } },
}]);
